___

<a href='https://oxiane-institut.com/'> <img src='../oxiane.jpg' /></a>
___

# Operations

There are many operations with pandas that will be really useful to you, but don't fit into any distinct category. Let's show them here in this lesson:

In [1]:
import pandas as pd

df = pd.DataFrame({'col1':[1,2,3,4],'col2':[444,555,666,444],'col3':['abc','def','ghi','xyz']})
df.head()

   col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

### Information sur les valeurs uniques:

In [2]:
df['col2'].unique()

array([444, 555, 666])

In [3]:
df['col2'].nunique()

3

In [4]:
df['col2'].value_counts()

col2
444    2
555    1
666    1
Name: count, dtype: int64

### Apply functions

In [5]:
df["col3"].apply(len)

0    3
1    3
2    3
3    3
Name: col3, dtype: int64

In [6]:
df = pd.read_csv("data/heart.csv")

In [7]:
# select_dtypes()
# 	exclude non numeric columns with 'object' dtype

df_numeric = df.select_dtypes(exclude=["object"])
df_numeric.head()

   age  pression  cholester  taux_max  depression  pic
0   70       130        322       109          24    2
1   67       115        564       160          16    2
2   57       124        261       141           3    1
3   64       128        263       105           2    2
4   74       120        269       121           2    1

In [8]:
# fonction call back
def operation_on_column(x):
    print(f"{type(x) = } {x.name = }")
    return(x.mean())


# Call the function on all columns of the DataFrame
resultat = df_numeric.apply(operation_on_column, axis=0)

# axis = 0
# 	each column will be passed to the function `operation()`

resultat

type(x) = <class 'pandas.core.series.Series'> x.name = 'age'
type(x) = <class 'pandas.core.series.Series'> x.name = 'pression'
type(x) = <class 'pandas.core.series.Series'> x.name = 'cholester'
type(x) = <class 'pandas.core.series.Series'> x.name = 'taux_max'
type(x) = <class 'pandas.core.series.Series'> x.name = 'depression'
type(x) = <class 'pandas.core.series.Series'> x.name = 'pic'

age            54.433333
pression      131.344444
cholester     249.659259
taux_max      149.677778
depression     10.500000
pic             1.585185
dtype: float64

In [14]:
# fonction call back
def operation_on_row(x):
    # print(f"{type(x) = } {x.shape = } {x.name = }")
    return x["age"] / x["depression"]
    # return x.mean()

resultat = df_numeric.apply(operation_on_row, axis=1)

# axis = 1
# 	each row will be passed as a Series to the function `operation()`

resultat

/tmp/ipykernel_102844/2860043273.py:4: RuntimeWarning: divide by zero encountered in scalar divide
  return x["age"] / x["depression"]

0       2.916667
1       4.187500
2      19.000000
3      32.000000
4      37.000000
         ...
265    10.400000
266          inf
267     4.307692
268    14.250000
269     4.466667
Length: 270, dtype: float64